# fly.toml app configuration file generated for my-react-portfolio-white-glade-1656 on 2024-01-13T10:21:25+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "my-react-portfolio-white-glade-1656"
primary_region = "ams"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
